apiVersion: v1
kind: ServiceAccount
metadata:
  name: generic-device-plugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generic-device-plugin-inventory
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: generic-device-plugin-inventory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: generic-device-plugin-inventory
subjects:
- kind: ServiceAccount
  name: generic-device-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      serviceAccountName: generic-device-plugin
      priorityClassName: system-node-critical
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: hys2023/generic-device-plugin:v0.0.1
        args:
        - --platform-devices
        - --device
        - |
          name: serial
          groups:
            - paths:
                - path: /dev/ttyUSB*
            - paths:
                - path: /dev/ttyACM*
            - paths:
                - path: /dev/tty.usb*
            - paths:
                - path: /dev/cu.*
            - paths:
                - path: /dev/cuaU*
            - paths:
                - path: /dev/rfcomm*
        name: generic-device-plugin
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 20Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: dbus
          mountPath: /run/dbus
          readOnly: true
        - name: udev
          mountPath: /run/udev
          readOnly: true
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: dbus
        hostPath:
          path: /run/dbus
      - name: udev
        hostPath:
          path: /run/udev
  updateStrategy:
    type: RollingUpdate
