apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "generic-device-plugin.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "generic-device-plugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "generic-device-plugin.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "generic-device-plugin.serviceAccountName" . }}
      priorityClassName: system-node-critical
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: generic-device-plugin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --platform-devices
          - --device
          - |
            name: fuse
            groups:
              - count: 10
                paths:
                  - path: /dev/fuse
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: dbus
              mountPath: /run/dbus
              readOnly: true
            - name: udev
              mountPath: /run/udev
              readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: dbus
          hostPath:
            path: /run/dbus
        - name: udev
          hostPath:
            path: /run/udev
  updateStrategy:
    type: RollingUpdate
